Creating a NumPy Array

Lets create a one dimensional Array(below). 

In [2]:
import numpy as np
list = [1,2,3,4,5]
array1 = np.array(list)
array1

array([1, 2, 3, 4, 5])

the data type is inferred from the data itself.
- We can set the datatype using "dtype"parameter

In [3]:
lst = [1,2,3,4,5,6,7]
arr = np.array(lst, dtype=float)
arr

array([1., 2., 3., 4., 5., 6., 7.])

We can create Multi-dimensional array using Nested List. Here is the example for the same.

In [4]:
names = [["john", "paul", "cruz"], ["Asmaa", "al", "Awdhi"], ['Avinash', "Kumar", "sheohar"]]
arr = np.array(names)
arr

array([['john', 'paul', 'cruz'],
       ['Asmaa', 'al', 'Awdhi'],
       ['Avinash', 'Kumar', 'sheohar']], dtype='<U7')

You CAN CHECK THE DIMENSION OF THE ARRAY USING "ndim" ATTRIBUTE

In [5]:
arr.ndim

2

"np.arange()" : 

THIS FUNCTION CREATES AN ARRAY WITH REGULARLY SPECED VALUE WITHIN A GIVEN RANGE. IT WORKS VERY SIMILAR TO AS PYTHON ARANGE FUNCTION WHEN APPLIED TO NUMBERS. HERE IS AN EXAMPLE OF HOW TO GENERATE AN ARRAY. THIS WILL CREATE A ONE DIMENSIONAL ARRAY OF NUMBER BETWEEN 0 TO 100 (NOT INCLUDING 100) WITH AN STEP SIZE OF 3

In [6]:
arr = np.arange(0, 100, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

"np.zeros()" : 

THIS FUCNTION CREATES AN ARRAY WITH ALL ITS ELEMENTS AS ZERO. DEFAULT DATA TYPE IS FLOAT. YOU CAN MENTION THE DATA TYPE PARAMETER 

In [7]:
arr = np.zeros((2,2), dtype=float)
arr

array([[0., 0.],
       [0., 0.]])

"np.ones()" : 

THIS FUNCTION CREATE AN ARRAY WITH ALL THE ELEMENTS AS ONES. DEFAULT DATATYPE IS FLOAT. YOU CAN PROVIDE THE DATATYPE USING DTYPE PARAMENTER

In [8]:
arr = np.ones((5,5), dtype=int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

"numpy.random.generator.integers" : 

THIS FUNCTION IS USED BY THE NUMPY LIBRARY TO GENERATE RANDOM INTEGERS WITHIN SPECIFIED RANGE OR WITH THE SPECIFIED SET OF VALUES.

Let’s say we want to create an array of random integers from 0 to 9, with 2 rows and 4 columns. First, we will create a random number generator, and then we will use the generator to generate the array. Here is how we can use this function to achieve that:

In [9]:
# CREATE A RANDOM NUMBER GENERATOR
rng = np.random.default_rng()

# GENERATE RANDOM INTEGER FROM 0 TO 9

rng.integers(low=0, high=100, size=(5,5))

array([[61,  4,  1, 83, 18],
       [28, 68, 66, 97, 26],
       [27, 14, 58, 47, 96],
       [ 9, 24, 34, 46, 22],
       [ 8, 14, 37, 39, 76]], dtype=int64)

Note: 

THE OUTPUT WILL ALWAYS VARY AS THEY ARE GENERATED RANDOMLY.

"numpy.random.generator.random":

THIS METHOD CREATES AN ARRAY OF RANDOM FLOATS. 

lETS CREATE AN ARRAY OF RANDOM FLOATS BETWEEN 0 AND 1, IN THE SHAPE OF 2 ROWS AND 5 COLUMNS.

In [10]:
rng = np.random.default_rng()
rng.random((2,5))

array([[0.3591069 , 0.63010143, 0.52079756, 0.26084701, 0.4822114 ],
       [0.01346594, 0.10088767, 0.252538  , 0.50146709, 0.87805165]])

SINCE OUTPUT IS RANDOM, YOU WILL GET DIFFERENT RESULT EVERYTIME YOU EXECUTE IT. TO ENSURE THAT THE OUTPUT IS REPRODUEABLE, WE SET THE "seed = 24". THIS MEANS THE THE GENERATED RANDOM STATE WILL BE REPEATED EVERYTIME YOU WILL RUN THE CODE.

In [11]:
rng = np.random.default_rng(seed=24)
rng.random((2,5))

array([[0.33026884, 0.40517732, 0.57473782, 0.50639977, 0.56421251],
       [0.56968731, 0.87411653, 0.08643046, 0.74247527, 0.82036726]])

ACCESSING ARRAY ELEMENTS : 

NUMPY ARRAY ARE INDEXED USING INTEGER STARTING FROM ZERO. HERE ARE FEW WAYS OF ACCESSING THE NUMPY ARRAY ELEMENTS.

1. SLICING
   This is similar to Python lists, where you can access a range of elements using a colon (:).

In [12]:
names = [["avinash", "kumar", "dubai"], ["raju", "babu", "sheohar"]]
arr = np.array(names)
arr

array([['avinash', 'kumar', 'dubai'],
       ['raju', 'babu', 'sheohar']], dtype='<U7')

In [13]:
select_sheohar = arr[1,2]
select_sheohar

'sheohar'

In [14]:
select_babu = arr[1,1]
select_babu

'babu'

In [15]:
select_avinash = arr[0,0]
select_avinash

'avinash'

LETS SAY YOU WANT TO SELECT THE NAMES "babu" AND "sheohar". HERE IS HOW YOU CAN USE SLICING FOR SUCH AN OPERATION

In [16]:
select_babu_sheohar = arr[1,1:]
select_babu_sheohar

array(['babu', 'sheohar'], dtype='<U7')

FANCY INDEXING: 
    This allows you to select elements based on a list of indices. LETS SAY IF YOU WANT TO SELECT THE ITEMS "dubai" and "sheohar" from the array, here is how we do it using fancy indexing.

In [17]:
# Creating an elements indices

select_dubai = np.array([0, 2])
select_sheohar = np.array([1, 2])

# Using fancy indexing to select

select_aa = arr[select_dubai]

IndexError: index 2 is out of bounds for axis 0 with size 2

ARRAY MANUPULAITON :
NumPy PROVIDES A WIDE RANGE OF FUNCTIONS TO MANIPULATE ARRAY, THEY ARE:
1. np.reshape()
2. np.concatenate()
3. np.split()
4. np.transpose()

np.reshape()
    We can change the shape of an array using the np.reshape()
    function. Here is how we can use reshape to flatten a multidimensional
    array. In the code above, we create a 2-dimensional array and then use the np.reshape() function to flatten the array. 
    The number 9 is the number of elements in the original array. By passing the number 9,
    we are telling the reshape function to return a 1-dimensional array.


In [ ]:
# Creating an array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flatten the array using reshape.

np.reshape(arr, 9)

In the code above, we create a 2-dimensional array and then use the np.reshape() function to flatten the array. The number 9 is the number of elements in the original array. By passing the number 9, we are telling the reshape function to return a 1-dimensional array.

Here is another example how to reshape the Array. we will reshape the array of names below.

In [24]:
name = [["jon", "Mary", "Paul"], ["Peter", "Ben", "Saul"]]
arr1 = np.array(name)
arr1

new_array = np.reshape(arr1, (3,2))
new_array

array([['jon', 'Mary'],
       ['Paul', 'Peter'],
       ['Ben', 'Saul']], dtype='<U5')

ARRAY MANUPULATION : np.concatenate()

This function joins two or more arrays together. We can pick the axis on which we want the arrays to be joined.
If we do not provide the axis, it will be joined on axis 0.

In [26]:
arr1 = np.array([[10,20,30], [40,50,60]])
arr2 = np.array([[100,110,120], [130,140,150]])

# Concatenate on Axis - 0

arr3 = np.concatenate((arr1, arr2), axis=0)
arr3

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [100, 110, 120],
       [130, 140, 150]])

Note that for concatenation to work, the arrays must have
the same number of dimensions. If we were to try to join
these two arrays on axis 1 (rows), we would get an error
because the two arrays do not have an equal number of
rows.

ARRAY MANUPULATION : np.split()

This function splits an array into smaller arrays. Below, we
use the np.split() function to split the array into two parts.

In [27]:
names = [["jon", "Mary", "paul"], ["Peter", "Ben", "Saul"]]

# Creating an Array
arr1 = np.array(names)

# using split to split the array into two parts.

split_one, split_two = np.split(arr1, 2)


In [28]:
split_one

array([['jon', 'Mary', 'paul']], dtype='<U5')

In [29]:
split_two


array([['Peter', 'Ben', 'Saul']], dtype='<U5')

ARRAY MANUPULATION : np.transpose()

This function transpose an array, by switching its rows and columns. Transposing an array, is specially useful when working woth Linear Algebra Operations such as Matrix multiplication.

In some cases, the multiplication of two natrices requires that one of the matrices be transposed in order for operation to be performed correctly.

In [30]:
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2 = np.array([[100,110,120], [130,140,150]])

# Perform dot operation and transpose Arr2

np.dot(arr1, arr2.transpose())

array([[ 6800,  8600],
       [16700, 21200],
       [26600, 33800]])

MATHEMATICAL FUNCTIONS

Numpy provides a wide range of mathematical functions that can be used on arrays. these include:
np.add(), np.subtract(), np.multiply(), np.divide(), np.power(), np.sqrt()
    

MATHEMETICAL FUNCTION: np.add() and np.subtract()

the "np.add()" adds two arrays together (element wide addition of two arrays, these crossponding elements from the ttwo arrays are added together.)

The "np.subtract()" function subtracts one array from another (element wise)

Here are the examples below:



In [31]:
arr1 = np.array([[1, 2, 4], [6, 7, 8]])
arr2 = np.array([[3, 3, 6], [4, 5, 6]])

# Adding two Arrays

np.add(arr1, arr2)

array([[ 4,  5, 10],
       [10, 12, 14]])

In [32]:
np.subtract(arr1, arr2)

array([[-2, -1, -2],
       [ 2,  2,  2]])