In [2]:
pip install pandas numpy matplotlib Sklearn seaborn

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/22/a5/a0b255295406ed54269814bc93723cfd1a0da63fb9aaf99e1364f07923e5/pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata
  Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/16/2e/86f24451c2d530c88daf997cb8d6ac622c1d40d19f5a031ed68a4b73a374/numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/7d/ca/e7bd1876a341ed8c456095962a582696cac1691cb6e55bd5ead15a755c5d/matplotlib-3.8.4-cp312-cp312-win_amd64.whl.metadata
  Using cached matplotlib-3.8.4-cp312-cp312-win_amd64.whl.metadata (5.9 kB)
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Get

  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.
  
  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
  
  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]
  
  note: This error originates f

In [1]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [1]:
!pip install pandas numpy matplotlib Sklearn seaborn

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ---------------------------------------- 61.0/61.0 kB 1.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.
  
  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
  
  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]
  
  note: This error originates f

In [2]:
!pip install pandas numpy matplotlib scikit-learn seaborn

  Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
  Using cached matplotlib-3.8.4-cp312-cp312-win_amd64.whl.metadata (5.9 kB)
     ---------------------------------------- 0.0/162.8 kB ? eta -:--:--
     ----------------- --------------------- 71.7/162.8 kB 3.8 MB/s eta 0:00:01
     -------------------------------------- 162.8/162.8 kB 4.8 MB/s eta 0:00:00
     ---------------------------------------- 0.0/60.6 kB ? eta -:--:--
     ---------------------------------------- 60.6/60.6 kB 3.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.4/11.5 MB 11.9 MB/s eta 0:00:01
   -- ------------------------------------- 0.7/11.5 MB 9.2 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.5 MB 8.2 MB/s eta 0:00:02
   ---- ----------------------------------- 1.4/11.5 MB 8.1 MB/s eta 0:00:02
   ------ --------

In [3]:
lst = [1,2,3]

In [4]:
ping lst


SyntaxError: invalid syntax (1720113266.py, line 1)

In [5]:
print lst

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (1652704894.py, line 1)

In [6]:
print(lst)

[1, 2, 3]


In [7]:
import numpy as np

lst = [1, 2, 3, 4, 5, 6]

#Creating and Array from a List

arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
## The Array datatype is inferred from the data . however, we can also set the data type using "dtype" parameter.

lst = [1, 2, 3, 4, 5, 6]
# creating an Array of  floats from list

arr = np.array(lst, dtype = float)
arr

array([1., 2., 3., 4., 5., 6.])

In [9]:
## you can create multidimensional array from nested list

names = [["jon", "Mary", "paul"], ["Peter", "Ben", "Saul"]]

arr1 = np.array(names)
arr1

array([['jon', 'Mary', 'paul'],
       ['Peter', 'Ben', 'Saul']], dtype='<U5')

In [10]:
arr.ndim


1

In [11]:
arr1.ndim

2

In [12]:
arr2 = np.arange(0, 50, 3)
arr2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [14]:
arr2=np.arange(0,50,5)
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
# Create Array with all elements as Zeros

arr3 = np.zeros((4,5), dtype=float)
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
## Create array of Ones

arr4 = np.ones((3,4), dtype=int)
arr4


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
## Lets say you want to create an array of Random integers from 0 to 9, with 2 rows and 4 columns.
## here first we will create a random number generator, and then we will use the generator to generate array.

# Creating a random number generator
rng = np.random.default_rng()

# Generate random integers from 0 to 9

rng.integer(low=0, high=10, size=(2,4))

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'integer'

In [20]:
## Lets say you want to create an array of Random integers from 0 to 9, with 2 rows and 4 columns.
## here first we will create a random number generator, and then we will use the generator to generate array.

# Creating a random number generator
rng = np.random.default_rng()

# Generate random integers from 0 to 9

rng.integers(low=0, high=10, size=(2,4))

array([[9, 2, 4, 9],
       [5, 1, 1, 9]], dtype=int64)