## Day5 - Array Creation and Vector Operations

In this challenge, you will create a 2-dimensional array,
analyze and perform vector operations on the array, and
slice numbers from the array.
list_numbers = [[12, 23, -45], [18, -77, -44]]
1. Using NumPy, create an array from the list. Write a code to
return all the negative numbers in the list.
2. Using NumPy, write code to multiply each element in the
array you created in question 1 by 2. Create a new variable
for this array.
3. Write code to calculate the sum of the numbers on axis-1 of
the array you created in question 2.
4. Write code to calculate the sum of numbers on axis-0 of the
array you created in question 2.
5. Using the NumPy arange() function, create a NumPy array
of numbers from 0 to 99. The shape of the array must be
(2, 5, 10).
6. Write code to slice row [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
from the array above (question 5).
7. Let’s analyze the array you created in question 1 further.
How many numbers in row 1 are greater than the numbers
in row 2?

In [1]:
list_numbers = [[12, 23, -45], [18, -77, -44]]
list_numbers

[[12, 23, -45], [18, -77, -44]]

## Task 1:
Using Numpy, create an array from the list. write a code to return all the negative numbers in the list

In [13]:
import numpy as np

# Create array from the List
arr = np.array(list_numbers)

# Useing Where function of Numpy to find out the Indexes of Negative numbers
negatives = np.where(arr <0)
print(arr[negatives])



[-45 -77 -44]


# Task 2
Using NumPy, write code to multiply each element in the array you created in question 1 by 2. Create a new variable for this array.

In [15]:
# Array was already created in the previous task, we will use that here 

arr1 = np.multiply(arr, 2)
arr1

# Also

#arr1 = arr*2
#arr1

array([[  24,   46,  -90],
       [  36, -154,  -88]])

## Task 3
Write code to calculate the sum of the numbers on axis-1 of the array you created in question 2.

In [20]:
arr2 = np.sum(arr1, axis=1)
arr2

array([ -20, -206])

## Task 4
Write code to calculate the sum of numbers on axis-0 of the array you created in question 2.

In [22]:
arr3 = np.sum(arr1, axis=0)
arr3

array([  60, -108, -178])

## Task 5
Using the NumPy arange() function, create a NumPy array of numbers from 0 to 99. The shape of the array must be (2, 5, 10).

In [24]:
arr4 = np.arange(100).reshape(2,5,10)
arr4

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

## Task 6
Write code to slice row [50, 51, 52, 53, 54, 55, 56, 57, 58, 59] from the array above (question 5).

In [26]:
arr4[1,0,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

## Task 7:
Let’s analyze the array you created in question 1 further. How many numbers in row 1 are greater than the numbers in row 2?

In [34]:
# First, we need to slice rows 1 and 2 from the array we created in question 1. We are going to use the NumPy greater() function to return the numbers in row one that are greater than the numbers in row two. This function will.
# return an array of Boolean values. If a number in row one is greater than a number in row 2, it will return True, and if it is not, it will return False. We will use the sum() function to sum the True values.

arr
#arr_row1 = arr[0,:]
#arr_row2 = arr[1,:]

# OR 
arr_row1 = arr[0]   # Selecting Row 1
arr_row2 = arr[1]   # Selecting Row 2
print("Row1 : ",arr_row1, "\nRow2 : ", arr_row2)    # Printhing poth the selected rows

# Using Greater than function

nums_greater = np.greater(arr_row1, arr_row2)
#nums_greater

print(f"The numbers in row 1 that are greater are: {sum(nums_greater)}")

Row1 :  [ 12  23 -45] 
Row2 :  [ 18 -77 -44]
The numbers in row 1 that are greater are: 1
