# Day 2: Creating and Manipulating Arrays

1. Write code to import NumPy into your script. Check the
version of NumPy installed.
2. Here is a list below:
list1 = [2, 3, 4, 6]
Create a one-dimensional array from the list above. Write
another line of code to check the shape and size of your
array.
Write a function that takes this array and returns a new
array with all the values in the original array reversed.
3. list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]
Create an array from the two lists above. Then write code to
check the shape, dimensions, and data type of the array.
4. list1 = [2, 3, 4, 6]
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1]
Create an array from the three (3) lists above. Take note
that some of the lists contain floats. Create an array that
will have an int64 data type.
5. Is it possible to create an array of both floats and integers?

## Importing Numpy and checking its verison

In [1]:
import numpy as np
np.version.version

# OR

print(np.__version__)

# OR

np.__version__
# Listing packages with version
#!pip list



1.26.4


'1.26.4'

## Creating an Array from the given list

In [2]:
# Creating Array from the List

list1 = [2,3,4,6]
arr1 = np.array(list1)
arr1

array([2, 3, 4, 6])

## Array Size

In [3]:
#  Size of the Array
arr1.size

4

In [4]:
# OR

arr_size = np.size(arr1)
arr_size

4

## Array Shape 

In [5]:
# Shape  of the Array
arr1.shape

(4,)

## Reversing the Array
there are 2 ways to reverse the array

In [6]:
# Option 1 - you define a function and pass the array to it to reverse it.

def reverse_array(array):
    return array[::-1]


arr2 = reverse_array(arr1)
arr2

array([6, 4, 3, 2])

In [7]:
# Option 2 - np.flip()

arr_flip = np.flip(arr1)
arr_flip

array([6, 4, 3, 2])

##  Create an array from the two lists. Then write code to check the shape, dimensions, and data type of the array.


In [8]:
# Create the array from the two list

list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]
arr1 = np.array([list1, list2])
arr1

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

### Array Shape

In [9]:
# Array Shape

arr1.shape

(2, 4)

### Array Size

In [10]:
# Array Size

arr1.size

8

### Array Dimension

In [11]:
# Array Dimension

arr1.ndim

2

### Array Data type

In [12]:
# Data type of the Array

arr1.dtype

dtype('int32')

You can see from the outputs that the shape of the array
will be (2, 4), which means it has 2 rows and 4 columns.
The dimensions of the array will be 2, indicating that it's a
2-dimensional array (arrays inside an array). The dtype
(data type) is int32.

## Create an array from the three (3) lists above. 
Take note that some of the lists contain floats. Create an array that will have an int64 data type.

Since some of our lists have some floating-point numbers,
when we create an array, the default data type will be
float64. That is why we need to convert it to an int64 data
type. To change the dtype, we can create an array using the
np.array() function and then use the astype() method to
convert the array to the desired data type of int64.

### Creating an Array from the lists

In [16]:
# Creating an Array from the lists

list1 = [2, 3, 4, 6] 
list2 = [8, 10.1, 12, 14] 
list3 = [16, 18, 20, 22.1] 

arr2 = np.array([list1, list2, list3],dtype=float)
arr2

array([[ 2. ,  3. ,  4. ,  6. ],
       [ 8. , 10.1, 12. , 14. ],
       [16. , 18. , 20. , 22.1]])

### Converting the attay to int64

In [17]:
arr3 = arr2.astype(np.int64)
arr3

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]], dtype=int64)

## Is it possible to create an array of both floats and integers?

In NumPy, an array is a homogeneous data structure,
which means that it can only hold values of a single data
type. Like we have seen above, if you have a list of floats
and integers and you want to convert it to an array, by
default it will be converted to the float data type.